### ISSUE TITLE
The "maximize zoom" feature does not really give full view

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/sd-simulate#3]
At least, that is something I recorded at some point. It would first need to be checked/reproduced if it is still an issue in the current version of the code. The misbehavior I recorded at the time was:

> The "maximize zoom" feature seems to have lost its full behavior. For example, loading `picture2.svg` and pressing the button, I get this:
> 
![282731018-b596f87c-b70b-46c8-b0ba-2ed9adc78315](https://github.com/fmidue/sd-simulate/assets/5853832/d93cf6ac-9139-4024-8685-e4349c07d495)
> not seeing the full diagram.

**Comment by DanielKonsek** [comment]
The described issue with the "maximize zoom" feature can not be reproduced with the current .svg files in the examples directory.

Do you still have the used "picture2.svg" or simmilar files?

**Comment by jvoigtlaender** [comment]
It was the file that is still there. But also on my end, I can't reproduce the issue as egregiously anymore. The zooming still always seems a bit off. For example, I now get this:
![image](https://github.com/fmidue/sd-simulate/assets/5853832/2efc6820-cece-4fc5-b58f-3dcd972a8f37)
There is just a bit of the picture missing, just so that a scroll bar appears on the right.

Analogously in vertical direction, with another example:
![image](https://github.com/fmidue/sd-simulate/assets/5853832/5d2a5ddd-667a-4a95-91ef-0dea691724ad)
If the small bit that is outside of the visible area here to the right would be brought into the visible area as well, the scroll bar at the bottom would disappear.
